name: Build and Test

run-name: ${{ github.actor }} is trying to make changes to the repository.

on: 
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
            
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Get python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'
        - name: Create .env file
          run: |
             echo "IP=${{ secrets.IP }}" >> personal_blog/.env
             echo "SECRET_KEY=123123123131" >> personal_blog/.env
             echo "URL=${{ secrets.URL }}" >> personal_blog/.env
        - name: install deps
          run: pip install -r requirements.txt
        
        - name: Collect static files
          run: python manage.py collectstatic --noinput
        - name: Migrate DB
          run: python manage.py migrate

        - name: run tests
          run: python manage.py test
        

